version: "3.9"

services:
  db:
    image: mariadb:latest
    container_name: wp_graphql-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: graphql_backend
      MYSQL_USER: graphql_backend
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORDPRESS_LANGUAGE: ${WORDPRESS_LANGUAGE}
    depends_on:
      - db
    image: wordpress-graphql:latest
    container_name: wp_graphql-wordpress
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_ADMIN_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_LANGUAGE: ${WORDPRESS_LANGUAGE}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: graphql_backend
      WORDPRESS_DB_USER: graphql_backend
      WORDPRESS_DB_PASSWORD: mypassword
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: wp_graphql-pma
    ports:
      - "8081:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  db_data:
